language: node_js
node_js:
  - "6"

sudo: required

services:
  - docker

install:
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install google-cloud-sdk
  - gcloud components install kubectl

before_script:
  - npm install -g angular-cli

script: ng build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t ng-seed .;
    fi
